x-go-service: &go-service
  build: .
  image: budgetms-go-base:local
  volumes:
    - ./src:/src
    - ./out:/out
  working_dir: /src
  depends_on:
    - db
  networks:
    - budgetMS_network

services:
  app:
    <<: *go-service
    profiles: ["app"]
    container_name: budgetMS-app
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    command: >
      sh -c "
      if [ ! -f go.mod ]; then
        go mod init main
      fi &&
      go mod tidy &&
      go build -o /out/main . &&
      /out/main app
      "
  api:
    <<: *go-service
    profiles: ["api"]
    container_name: budgetMS-api
    ports:
      - "8081:8080"
    tty: true
    stdin_open: true
    command: >
      sh -c "
      if [ ! -f go.mod ]; then
        go mod init main
      fi &&
      go mod tidy &&
      go build -o /out/main . &&
      /out/main api
      "
  init:
    <<: *go-service
    container_name: budgetMS-init
    profiles: ["init"]
    command: >
      sh -c "
      go mod tidy &&
      go build -o /out/main . &&
      /out/main setup
      "

  db:
    image: postgres:16-alpine
    container_name: budgetMS-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budgetMS
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - budgetMS_network

volumes:
  db_data:

networks:
  budgetMS_network:
    driver: bridge
    name: budgetMS_network
