version: "3.9"

services:
  sv-dev:
    build:
      context: .
      dockerfile: Dockerfile.server-dev
    container_name: home-portal-dev
    stdin_open: true
    tty: true
    working_dir: /src
    volumes:
      - ./server:/src
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    depends_on:
      - db
    networks:
      - home-portal_network 
    command: "sh"
    ports:
      - "8080:8080"



  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.front-dev
    container_name: home-portal-web
    profiles: ["web-dev"]
    volumes:
      - ./web:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    networks:
      - home-portal_network

  db:
    image: postgres:16-alpine
    container_name: home-portal-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: home-portal
      TZ: Asia/Tokyo
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - home-portal_network

volumes:
  db_data:
  go-mod-cache:
  go-build-cache:

networks:
  home-portal_network:
    driver: bridge
