x-go-service: &go-service
  build:
    context: .
    dockerfile: Dockerfile.api-server
  image: home-portal-go:latest
  volumes:
    - ./server:/src
  working_dir: /src
  depends_on:
    - db
  networks:
    - home-portal_network

services:
  api:
    <<: *go-service
    profiles: ["api"]
    container_name: home-portal-api
    ports:
      - "8081:8080"
    tty: true
    stdin_open: true
    command: >
      sh -c "
      if [ ! -f go.mod ]; then
        go mod init main
      fi &&
      go mod tidy &&
      go build -o /out/main . &&
      /out/main api
      "
  setup:
    <<: *go-service
    container_name: home-portal-setup
    profiles: ["setup"]
    command: >
      sh -c "
      go mod tidy &&
      go build -o /out/main . &&
      /out/main setup
      "

  web:
    build:
      context: .
      dockerfile: Dockerfile.front
    image: home-portal-web:latest
    container_name: home-portal-web
    volumes:
      - ./web:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c " npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    networks:
      - home-portal_network
  db:
    image: postgres:16-alpine
    container_name: home-portal-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: home-portal
      TZ: Asia/Tokyo
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - home-portal_network

volumes:
  db_data:

networks:
  home-portal_network:
    driver: bridge
    name: home-portal_network